//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json;


namespace My.Template.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Action
    {
        public Action()
        {
            this.ASequence = 0;
            this.IsDelete = false;
            this.IsFrozen = false;
            this.ParentID = 0;
            this.User_Action = new HashSet<User_Action>();
            this.Role_Action = new HashSet<Role_Action>();
        }
    
        public int ID { get; set; }
        public string AName { get; set; }
        public string AUrl { get; set; }
        public string AIcon { get; set; }
        public int ASequence { get; set; }
        public bool IsDelete { get; set; }
        public bool IsFrozen { get; set; }
        public int ParentID { get; set; }
        public int ActionTypeID { get; set; }
    
    	[JsonIgnore]
        public virtual ICollection<User_Action> User_Action { get; set; }
    	[JsonIgnore]
        public virtual ICollection<Role_Action> Role_Action { get; set; }
    	[JsonIgnore]
        public virtual ActionType ActionType { get; set; }
    }
}
