//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace My.Template.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataModelContainer : DbContext
    {
        public DataModelContainer()
            : base("name=DataModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<User> User { get; set; }
        public DbSet<UserInfo> UserInfo { get; set; }
        public DbSet<Role> Role { get; set; }
        public DbSet<User_Role> User_Role { get; set; }
        public DbSet<Action> Action { get; set; }
        public DbSet<User_Action> User_Action { get; set; }
        public DbSet<Role_Action> Role_Action { get; set; }
        public DbSet<ActionType> ActionType { get; set; }
        public DbSet<Banner> Banner { get; set; }
        public DbSet<SinglePage> SinglePage { get; set; }
        public DbSet<News> News { get; set; }
        public DbSet<SiteInfo> SiteInfo { get; set; }
        public DbSet<NewsType> NewsType { get; set; }
        public DbSet<Videos> Videos { get; set; }
        public DbSet<QAInfos> QAInfos { get; set; }
        public DbSet<BannerType> BannerType { get; set; }
        public DbSet<Notice> Notice { get; set; }
        public DbSet<User_ShoppingCart> User_ShoppingCart { get; set; }
        public DbSet<GoodsInfo> GoodsInfo { get; set; }
        public DbSet<GoodsProperty> GoodsProperty { get; set; }
        public DbSet<GoodsPropertyDetail> GoodsPropertyDetail { get; set; }
        public DbSet<GoodsType> GoodsType { get; set; }
        public DbSet<Order> Order { get; set; }
        public DbSet<OrderStatus> OrderStatus { get; set; }
        public DbSet<OrderGoods> OrderGoods { get; set; }
        public DbSet<RecAddress> RecAddress { get; set; }
        public DbSet<CityInfo> CityInfo { get; set; }
        public DbSet<Community> Community { get; set; }
        public DbSet<AreaInfo> AreaInfo { get; set; }
        public DbSet<SampleHouse> SampleHouse { get; set; }
        public DbSet<HouseArea> HouseArea { get; set; }
        public DbSet<SpHouse_HseArea> SpHouse_HseArea { get; set; }
    }
}
