//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace My.Template.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodsProperty
    {
        public GoodsProperty()
        {
            this.GoodsPropertyDetail = new HashSet<GoodsPropertyDetail>();
        }
    
        public int ID { get; set; }
        public int GoodsInfoID { get; set; }
        public bool IsDelete { get; set; }
        public string GPName { get; set; }
        public int Sequence { get; set; }
    
        public virtual GoodsInfo GoodsInfo { get; set; }
        public virtual ICollection<GoodsPropertyDetail> GoodsPropertyDetail { get; set; }
    }
}
