//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json;


namespace My.Template.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodsInfo : IBaseEntity
    {
        public GoodsInfo()
        {
            this.GoodsProperty = new HashSet<GoodsProperty>();
        }
    
        public int ID { get; set; }
        public string SkuNumber { get; set; }
        public int GoodsTypeID { get; set; }
        public bool IsDelete { get; set; }
        public bool IsView { get; set; }
        public bool IsView4HomePage { get; set; }
        public string GShortName { get; set; }
        public string GFullName { get; set; }
        public int Price { get; set; }
        public string ThumbPic { get; set; }
        public string DetailPics { get; set; }
        public int Sequence { get; set; }
        public int DeliveryDate { get; set; }
    
    	[JsonIgnore]
        public virtual ICollection<GoodsProperty> GoodsProperty { get; set; }
    	[JsonIgnore]
        public virtual GoodsType GoodsType { get; set; }
    }
}
