//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json;


namespace My.Template.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodsSkuPrice_R_GoodsProDetails : IBaseEntity
    {
        public int ID { get; set; }
        public string GoodsPropertyID { get; set; }
        public int GoodsPropertyDetailID { get; set; }
        public int GoodsSkuPriceID { get; set; }
        public string GoodsInfoID { get; set; }
        public bool IsDelete { get; set; }
    
    	[JsonIgnore]
        public virtual GoodsSkuPrice GoodsSkuPrice { get; set; }
    }
}
