//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace My.Template.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HouseArea
    {
        public HouseArea()
        {
            this.SpHouse_HseArea = new HashSet<SpHouse_HseArea>();
        }
    
        public int ID { get; set; }
        public string AName { get; set; }
    
        public virtual ICollection<SpHouse_HseArea> SpHouse_HseArea { get; set; }
    }
}
