//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json;


namespace My.Template.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class News : IBaseEntity
    {
        public News()
        {
            this.IsView = true;
            this.Sequence = 0;
            this.ClickNum = 0;
            this.IsDelete = false;
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public bool IsView { get; set; }
        public int Sequence { get; set; }
        public int ClickNum { get; set; }
        public System.DateTime AddTime { get; set; }
        public bool IsDelete { get; set; }
        public string SeoKeywords { get; set; }
        public string SeoDescription { get; set; }
        public int NewsTypeID { get; set; }
    
    	[JsonIgnore]
        public virtual NewsType NewsType { get; set; }
    }
}
