//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json;


namespace My.Template.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderGoods
    {
        public int ID { get; set; }
        public int OrderID { get; set; }
        public string GoodsInfoID { get; set; }
        public string GoodsPropertyInfos { get; set; }
        public int Count { get; set; }
        public int CurPrice { get; set; }
    
    	[JsonIgnore]
        public virtual Order Order { get; set; }
    }
}
