//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace My.Template.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecAddress
    {
        public RecAddress()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int ID { get; set; }
        public bool IsDelete { get; set; }
        public bool IsDefault { get; set; }
        public string Title { get; set; }
        public string RecvicerName { get; set; }
        public string Mobile { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string Area { get; set; }
        public string Detail { get; set; }
        public string ZipCode { get; set; }
        public int UserID { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<Order> Order { get; set; }
    }
}
