//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace My.Template.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SinglePage
    {
        public SinglePage()
        {
            this.IsDelete = false;
        }
    
        public int ID { get; set; }
        public string PageName { get; set; }
        public string PageContent { get; set; }
        public string SeoKeyWord { get; set; }
        public string SeoDescription { get; set; }
        public System.DateTime AddTime { get; set; }
        public bool IsDelete { get; set; }
        public int Sequence { get; set; }
        public bool IsView { get; set; }
    }
}
