//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json;


namespace My.Template.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteInfo : IBaseEntity
    {
        public SiteInfo()
        {
            this.IsViewInfo = false;
        }
    
        public int ID { get; set; }
        public string SiteName { get; set; }
        public string SiteUrl { get; set; }
        public string CompanyName { get; set; }
        public string Address { get; set; }
        public string ZipCode { get; set; }
        public string Telephone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string SeoKeyWords { get; set; }
        public string SeoDescription { get; set; }
        public string IcpNumber { get; set; }
        public bool IsViewInfo { get; set; }
    }
}
