//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace My.Template.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.IsDelete = false;
            this.IsFrozen = false;
            this.User_Role = new HashSet<User_Role>();
            this.User_Action = new HashSet<User_Action>();
            this.User_ShoppingCart = new HashSet<User_ShoppingCart>();
            this.RecAddress = new HashSet<RecAddress>();
        }
    
        public int ID { get; set; }
        public string Account { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string WxOpenid { get; set; }
        public string SinaWBOpenid { get; set; }
        public string QQNum { get; set; }
        public string Pwd { get; set; }
        public bool IsDelete { get; set; }
        public bool IsFrozen { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int Balance { get; set; }
        public int FrozenBlance { get; set; }
        public string AlipayAccount { get; set; }
        public string BankNumber { get; set; }
        public string BankName { get; set; }
    
        public virtual ICollection<User_Role> User_Role { get; set; }
        public virtual ICollection<User_Action> User_Action { get; set; }
        public virtual UserInfo UserInfo { get; set; }
        public virtual ICollection<User_ShoppingCart> User_ShoppingCart { get; set; }
        public virtual ICollection<RecAddress> RecAddress { get; set; }
    }
}
